### ISSUE TITLE
step_len is added twice to check it exceeds len(self.price)

### ISSUE THREAD

**Issue by jsrimr** [Yvictor/TradingGym#13]
https://github.com/Yvictor/TradingGym/blob/8af2bb02250797c580b37c7ef43aab21b2d968c7/trading_env/envs/training_v1.py#L183-L207

Maybe line 207 should be changed from 
```
 if self.step_st+self.obs_len+self.step_len >= len(self.price):
```
to 
```
 if self.step_st+self.obs_len >= len(self.price):
```

**Comment by DenisLitvin** [comment]
It looks correct. imagine step_st is a current index/step in a states array, whereas step_len is just an amount of steps it jumps when iterating
