### ISSUE TITLE
'trading_env' object has no attribute 'backtest'

### ISSUE THREAD

**Issue by zzxxcc7412** [Yvictor/TradingGym#6]
[2018-01-09 18:15:10,379] Making new env: backtest_v1

Traceback (most recent call last):
  File "D:/AutoTrade/train.py", line 25, in <module>
    state = env.backtest()
AttributeError: 'trading_env' object has no attribute 'backtest'

What's can I do?
please help!

**Comment by Letni1** [comment]
Hey, did u fix this?

**Comment by irvineAlgotrading** [comment]
please reopen, i am having the same issue!

**Comment by hx173149** [comment]
I have the same problem

**Comment by poposkygyq1983** [comment]
add a function "backtest" in the backtest_v1.py
